### PR TITLE
Add linting

### PR DESCRIPTION
**Pull request by tillywoodfield**
- Add black, isort, flake8
- Format code to comply (mostly quotes and line lengths)
- Add github actions workflow for lint checks

### CODE REVIEW

**Comment by Bjwebb** [comment]
BTW, it's preferable to set a different author for the black reformatting, so that your name isn't next to many lines in git blame. Here's an example from another repo https://github.com/OpenDataServices/flatten-tool/commit/a094fea22d143c150e9cb918b2cb24e964de844c

**Comment by tillywoodfield** [comment]
> BTW, it's preferable to set a different author for the black reformatting, so that your name isn't next to many lines in git blame. Here's an example from another repo [OpenDataServices/flatten-tool@a094fea](https://github.com/OpenDataServices/flatten-tool/commit/a094fea22d143c150e9cb918b2cb24e964de844c)

@Bjwebb that makes sense, thank you, I've updated the first commit to use that author

**Review by odscjames — APPROVED** [review]

**Comment by odscjames** [comment]
> flake8 iatidata/

Extremely pedantically, we have this in the github actions (using paths with all the lint tools) which is great but can it be in the readme too? Otherwise sometimes peoples virtual environments get processed too which takes a while and gives many false alerts. We can do that in another PR tho.

**Comment by tillywoodfield** [comment]
> > flake8 iatidata/
> 
> Extremely pedantically, we have this in the github actions (using paths with all the lint tools) which is great but can it be in the readme too? Otherwise sometimes peoples virtual environments get processed too which takes a while and gives many false alerts. We can do that in another PR tho.

@odscjames Please could you clarify, I had [this](https://github.com/codeforIATI/iati-tables/pull/22/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) in the readme, do you want me to add something else?

**Comment by odscjames** [comment]
You totally did, I apologise! Not sure how I got that wrong.

**Pull request merged**
